-- The Perch: bookings, blocked dates and the staff list.
--
-- Guest details live only in `bookings`, which anonymous visitors cannot read.
-- The website learns which nights are taken through the `occupancy` view.

create extension if not exists btree_gist with schema extensions;

-- ---------------------------------------------------------------------------
-- Booking references: PRC-xxxxx, unique, generated by the database so the
-- website and the offline form never race each other.
-- ---------------------------------------------------------------------------
create or replace function public.new_booking_ref()
returns text
language plpgsql
volatile
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := 'PRC-' || (floor(random() * 90000) + 10000)::int::text;
    exit when not exists (select 1 from public.bookings where ref = candidate);
  end loop;
  return candidate;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table public.bookings (
  ref              text primary key default public.new_booking_ref(),
  apartment_id     integer not null,
  check_in         date not null,
  check_out        date not null,
  adults           integer not null default 1 check (adults >= 1),
  children         integer not null default 0 check (children >= 0),
  guest_name       text not null,
  guest_email      text not null default '',
  guest_phone      text not null default '',
  guest_whatsapp   text not null default '',
  arrival_time     text not null default '',
  payment          text not null
                   check (payment in ('paystack', 'flutterwave', 'transfer', 'arrival', 'cash', 'other')),
  -- Stay total including fees and deposit, in naira.
  total            integer not null check (total >= 0),
  status           text not null default 'pending'
                   check (status in ('pending', 'confirmed', 'cancelled')),
  source           text not null default 'website'
                   check (source in ('website', 'offline')),
  note             text not null default '',
  -- Payment tracking (filled in by the Paystack integration, phase 1).
  payment_status   text not null default 'unpaid'
                   check (payment_status in ('unpaid', 'paid', 'failed', 'refunded')),
  payment_ref      text,
  payment_channel  text,
  paid_amount      integer check (paid_amount is null or paid_amount >= 0),
  paid_at          timestamptz,
  -- While unpaid, when the held nights go back on sale. Null means no automatic expiry.
  hold_expires_at  timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  constraint bookings_dates_ordered check (check_out > check_in),
  -- Two live bookings can never hold the same apartment on the same night.
  constraint bookings_no_double_booking exclude using gist (
    apartment_id with =,
    daterange(check_in, check_out, '[)') with &&
  ) where (status <> 'cancelled')
);

create index bookings_apartment_dates_idx on public.bookings (apartment_id, check_in, check_out);
create index bookings_created_at_idx on public.bookings (created_at desc);
create index bookings_hold_expiry_idx on public.bookings (hold_expires_at)
  where payment_status = 'unpaid' and status = 'pending' and hold_expires_at is not null;

create table public.date_blocks (
  id            text primary key default 'blk-' || substr(md5(random()::text), 1, 12),
  apartment_id  integer not null,
  start_date    date not null,
  -- Exclusive, like a check-out date: the morning the room is free again.
  end_date      date not null,
  reason        text not null default '',
  created_at    timestamptz not null default now(),

  constraint date_blocks_dates_ordered check (end_date > start_date),
  constraint date_blocks_no_overlap exclude using gist (
    apartment_id with =,
    daterange(start_date, end_date, '[)') with &&
  )
);

create index date_blocks_apartment_dates_idx on public.date_blocks (apartment_id, start_date, end_date);

-- Staff who may use the admin area. Rows are added with grant_admin(), below.
create table public.admins (
  user_id     uuid primary key references auth.users (id) on delete cascade,
  email       text not null,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger bookings_touch_updated_at
  before update on public.bookings
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Access control
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

revoke execute on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- Run from the SQL editor after creating the user under Authentication:
--   select public.grant_admin('staff@example.com');
create or replace function public.grant_admin(user_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid;
begin
  select id into uid from auth.users where lower(email) = lower(user_email);
  if uid is null then
    raise exception 'No auth user with email %; create the user first.', user_email;
  end if;
  insert into public.admins (user_id, email) values (uid, lower(user_email))
  on conflict (user_id) do nothing;
end;
$$;

revoke execute on function public.grant_admin(text) from public, anon, authenticated;

alter table public.bookings    enable row level security;
alter table public.date_blocks enable row level security;
alter table public.admins      enable row level security;

-- Anonymous visitors get no direct access to any table; the edge function
-- writes bookings with the service role and the occupancy view serves reads.
create policy "admins manage bookings" on public.bookings
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins manage blocks" on public.date_blocks
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "users can see their own admin row" on public.admins
  for select to authenticated
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Public occupancy: which nights are taken, with no guest data.
-- The view deliberately runs with its owner's rights (not security_invoker)
-- so anonymous visitors can read it although they cannot read `bookings`.
-- ---------------------------------------------------------------------------
create view public.occupancy
with (security_invoker = false)
as
  select
    ref          as id,
    'booking'    as kind,
    apartment_id,
    check_in     as start_date,
    check_out    as end_date,
    status
  from public.bookings
  where status <> 'cancelled'
  union all
  select
    id,
    'block',
    apartment_id,
    start_date,
    end_date,
    'blocked'
  from public.date_blocks;

grant select on public.occupancy to anon, authenticated;

-- Live updates for the admin screen. Row-level security still applies, so
-- only signed-in staff receive change events.
alter publication supabase_realtime add table public.bookings;
alter publication supabase_realtime add table public.date_blocks;
